{{- $values := .Values.ingress -}}
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: {{ template "weechat.fullname" . }}
  annotations:
  {{- if $values.annotations }}
  annotations:
    {{- with $values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.hostUrl }}
    secretName: "{{ template "weechat.fullname" . }}-cert"
  rules:
  - host: {{ .Values.hostUrl }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "weechat.fullname" . }}
            port: 
              number: 80
