apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gb.fullname" . }}
  labels:
    app: {{ template "gb.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "gb.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "gb.fullname" . }}
    spec:
      containers:
      - name: {{ template "gb.fullname" . }}
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        ports:
        - name: gb
          containerPort: 80
        resources:
{{ toYaml .Values.resources | indent 10 }}
